---------------------------------------------------------------------------------------------------------- 
--------------------------- All Copy Rights are reserved to Tasko.in-------------------------------------- 
USE [Tasko] 
GO 
---------------------------------------------------------------------------------------------------------- 
    
-------- Services TestData --------------
INSERT INTO [dbo].[Services] values(NEWID(),'Electrician',null,'http://api.tasko.in/serviceimages/electrician.png',0)
INSERT INTO [dbo].[Services] values(NEWID(),'Microwave Service',null,'http://api.tasko.in/serviceimages/Microwave_Service.png',0)
INSERT INTO [dbo].[Services] values(NEWID(),'Refrigerator Service',null,'http://api.tasko.in/serviceimages/Refrigerator_Service.png',0)
INSERT INTO [dbo].[Services] values(NEWID(),'Pest Control',null, 'http://api.tasko.in/serviceimages/bug.png',0)
INSERT INTO [dbo].[Services] values(NEWID(),'Carpentry',null,'http://api.tasko.in/serviceimages/carpenter.png',0)
INSERT INTO [dbo].[Services] values(NEWID(),'Water Purifier Installtion',null,'http://api.tasko.in/serviceimages/water-purifier.png',0)
INSERT INTO [dbo].[Services] values(NEWID(),'House Cleaning',null,'http://api.tasko.in/serviceimages/house_services.png',0)
INSERT INTO [dbo].[Services] values(NEWID(),'AC Installation',null,'http://api.tasko.in/serviceimages/ac_services.png',0)
INSERT INTO [dbo].[Services] values(NEWID(),'Fully Automatic Washing Machine Service',null,'http://api.tasko.in/serviceimages/Washing_Machine_Service.png',0)
INSERT INTO [dbo].[Services] values(NEWID(),'AC Service',null,'http://api.tasko.in/serviceimages/ac_services.png',0)
INSERT INTO [dbo].[Services] values(NEWID(),'Semi-Automatic Washing Machine Service',null,'http://api.tasko.in/serviceimages/Washing_Machine_Service.png',0)
INSERT INTO [dbo].[Services] values(NEWID(),'Bike Service',null,'http://api.tasko.in/serviceimages/Bike_Service.png',0)
INSERT INTO [dbo].[Services] values(NEWID(),'Mixer Grinder Repair',null,'http://api.tasko.in/serviceimages/Mixer_Grinder_Repair.png',0)
INSERT INTO [dbo].[Services] values(NEWID(),'Water Purifier Service',null,'http://api.tasko.in/serviceimages/water-purifier.png',0)
INSERT INTO [dbo].[Services] values(newid(), 'Plumber',null, 'http://api.tasko.in/serviceimages/plumber.png',0)

SELECT * FROM [dbo].[Services]
  
------------ ID Proof TestData -----------
INSERT INTO [dbo].[ID_PROOFS] values(NEWID(),'PAN Card')
INSERT INTO [dbo].[ID_PROOFS] values(NEWID(),'Passport')
INSERT INTO [dbo].[ID_PROOFS] values(NEWID(),'Aadhar Card')
INSERT INTO [dbo].[ID_PROOFS] values(NEWID(),'Voter Id')
SELECT * FROM [dbo].[ID_PROOFS]

----- Order Status TestData-----
INSERT INTO [dbo].[ORDER_STATUS] values(1, 'OrderPending')
INSERT INTO [dbo].[ORDER_STATUS] values(2, 'OrderAccepted')
INSERT INTO [dbo].[ORDER_STATUS] values(3, 'OrderConfirmed')
INSERT INTO [dbo].[ORDER_STATUS] values(4, 'OrderCancelled')
INSERT INTO [dbo].[ORDER_STATUS] values(5, 'OrderWorkCompleted')
INSERT INTO [dbo].[ORDER_STATUS] values(6, 'OrderCompleted')
INSERT INTO [dbo].[ORDER_STATUS] values(7, 'OrderMissed')
INSERT INTO [dbo].[ORDER_STATUS] values(8, 'OrderRejected')
SELECT * FROM [dbo].[ORDER_STATUS]

INSERT INTO [dbo].[USER] VALUES(NEWID(),'admin','Administrator', 'admin', 'admin@Tasko.in', 1234567890,1,getdate(),1)

insert into CUSTOMER_PINCODE values (newid(), '500001')
insert into CUSTOMER_PINCODE values (newid(), '500002')
insert into CUSTOMER_PINCODE values (newid(), '500003')
insert into CUSTOMER_PINCODE values (newid(), '500004')
insert into CUSTOMER_PINCODE values (newid(), '500005')
insert into CUSTOMER_PINCODE values (newid(), '500006')
insert into CUSTOMER_PINCODE values (newid(), '500007')
insert into CUSTOMER_PINCODE values (newid(), '500008')
insert into CUSTOMER_PINCODE values (newid(), '500009')
insert into CUSTOMER_PINCODE values (newid(), '500010')
insert into CUSTOMER_PINCODE values (newid(), '500011')
insert into CUSTOMER_PINCODE values (newid(), '500012')
insert into CUSTOMER_PINCODE values (newid(), '500013')
insert into CUSTOMER_PINCODE values (newid(), '500014')
insert into CUSTOMER_PINCODE values (newid(), '500015')
insert into CUSTOMER_PINCODE values (newid(), '500016')
insert into CUSTOMER_PINCODE values (newid(), '500017')
insert into CUSTOMER_PINCODE values (newid(), '500018')
insert into CUSTOMER_PINCODE values (newid(), '500019')
insert into CUSTOMER_PINCODE values (newid(), '500020')
insert into CUSTOMER_PINCODE values (newid(), '500021')
insert into CUSTOMER_PINCODE values (newid(), '500022')
insert into CUSTOMER_PINCODE values (newid(), '500023')
insert into CUSTOMER_PINCODE values (newid(), '500024')
insert into CUSTOMER_PINCODE values (newid(), '500025')
insert into CUSTOMER_PINCODE values (newid(), '500026')
insert into CUSTOMER_PINCODE values (newid(), '500027')
insert into CUSTOMER_PINCODE values (newid(), '500028')
insert into CUSTOMER_PINCODE values (newid(), '500029')
insert into CUSTOMER_PINCODE values (newid(), '500030')
insert into CUSTOMER_PINCODE values (newid(), '500031')
insert into CUSTOMER_PINCODE values (newid(), '500032')
insert into CUSTOMER_PINCODE values (newid(), '500033')
insert into CUSTOMER_PINCODE values (newid(), '500034')
insert into CUSTOMER_PINCODE values (newid(), '500035')
insert into CUSTOMER_PINCODE values (newid(), '500036')
insert into CUSTOMER_PINCODE values (newid(), '500037')
insert into CUSTOMER_PINCODE values (newid(), '500038')
insert into CUSTOMER_PINCODE values (newid(), '500039')
insert into CUSTOMER_PINCODE values (newid(), '500040')
insert into CUSTOMER_PINCODE values (newid(), '500041')
insert into CUSTOMER_PINCODE values (newid(), '500042')
insert into CUSTOMER_PINCODE values (newid(), '500043')
insert into CUSTOMER_PINCODE values (newid(), '500044')
insert into CUSTOMER_PINCODE values (newid(), '500045')
insert into CUSTOMER_PINCODE values (newid(), '500046')
insert into CUSTOMER_PINCODE values (newid(), '500047')
insert into CUSTOMER_PINCODE values (newid(), '500048')
insert into CUSTOMER_PINCODE values (newid(), '500049')
insert into CUSTOMER_PINCODE values (newid(), '500050')
insert into CUSTOMER_PINCODE values (newid(), '500051')
insert into CUSTOMER_PINCODE values (newid(), '500052')
insert into CUSTOMER_PINCODE values (newid(), '500053')
insert into CUSTOMER_PINCODE values (newid(), '500054')
insert into CUSTOMER_PINCODE values (newid(), '500055')
insert into CUSTOMER_PINCODE values (newid(), '500056')
insert into CUSTOMER_PINCODE values (newid(), '500057')
insert into CUSTOMER_PINCODE values (newid(), '500058')
insert into CUSTOMER_PINCODE values (newid(), '500059')
insert into CUSTOMER_PINCODE values (newid(), '500060')
insert into CUSTOMER_PINCODE values (newid(), '500061')
insert into CUSTOMER_PINCODE values (newid(), '500062')
insert into CUSTOMER_PINCODE values (newid(), '500063')
insert into CUSTOMER_PINCODE values (newid(), '500064')
insert into CUSTOMER_PINCODE values (newid(), '500065')
insert into CUSTOMER_PINCODE values (newid(), '500066')
insert into CUSTOMER_PINCODE values (newid(), '500067')
insert into CUSTOMER_PINCODE values (newid(), '500068')
insert into CUSTOMER_PINCODE values (newid(), '500069')
insert into CUSTOMER_PINCODE values (newid(), '500070')
insert into CUSTOMER_PINCODE values (newid(), '500071')
insert into CUSTOMER_PINCODE values (newid(), '500072')
insert into CUSTOMER_PINCODE values (newid(), '500073')
insert into CUSTOMER_PINCODE values (newid(), '500074')
insert into CUSTOMER_PINCODE values (newid(), '500075')
insert into CUSTOMER_PINCODE values (newid(), '500076')
insert into CUSTOMER_PINCODE values (newid(), '500077')
insert into CUSTOMER_PINCODE values (newid(), '500078')
insert into CUSTOMER_PINCODE values (newid(), '500079')
insert into CUSTOMER_PINCODE values (newid(), '500080')
insert into CUSTOMER_PINCODE values (newid(), '500081')
insert into CUSTOMER_PINCODE values (newid(), '500082')
insert into CUSTOMER_PINCODE values (newid(), '500083')
insert into CUSTOMER_PINCODE values (newid(), '500084')
insert into CUSTOMER_PINCODE values (newid(), '500085')
insert into CUSTOMER_PINCODE values (newid(), '500086')
insert into CUSTOMER_PINCODE values (newid(), '500087')
insert into CUSTOMER_PINCODE values (newid(), '500088')
insert into CUSTOMER_PINCODE values (newid(), '500089')
insert into CUSTOMER_PINCODE values (newid(), '500090')
insert into CUSTOMER_PINCODE values (newid(), '500091')
insert into CUSTOMER_PINCODE values (newid(), '500092')
insert into CUSTOMER_PINCODE values (newid(), '500093')
insert into CUSTOMER_PINCODE values (newid(), '500094')
insert into CUSTOMER_PINCODE values (newid(), '500095')
insert into CUSTOMER_PINCODE values (newid(), '500096')
insert into CUSTOMER_PINCODE values (newid(), '500097')
insert into CUSTOMER_PINCODE values (newid(), '500098')
insert into CUSTOMER_PINCODE values (newid(), '500099')
insert into CUSTOMER_PINCODE values (newid(), '500100')
insert into CUSTOMER_PINCODE values (newid(), '501510')
insert into CUSTOMER_PINCODE values (newid(), '502032')
insert into CUSTOMER_PINCODE values (newid(), '500133')
insert into CUSTOMER_PINCODE values (newid(), '501401')
insert into CUSTOMER_PINCODE values (newid(), '502325')


SELECT * FROM CUSTOMER_PINCODE

