//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tasko {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tasko.CommonMessages", typeof(CommonMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed.
        /// </summary>
        internal static string AUTHENTICATION_FAILED {
            get {
                return ResourceManager.GetString("AUTHENTICATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Successful.
        /// </summary>
        internal static string AUTHENTICATION_SUCCESSFULL {
            get {
                return ResourceManager.GetString("AUTHENTICATION_SUCCESSFULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Address Invalid.
        /// </summary>
        internal static string CUSTOMER_ADDRESS_INVALID {
            get {
                return ResourceManager.GetString("CUSTOMER_ADDRESS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Addresses not found.
        /// </summary>
        internal static string CUSTOMER_ADDRESS_NOT_FOUND {
            get {
                return ResourceManager.GetString("CUSTOMER_ADDRESS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Id and address are mandatory.
        /// </summary>
        internal static string CUSTOMER_DETAILS_INVALID {
            get {
                return ResourceManager.GetString("CUSTOMER_DETAILS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer not found.
        /// </summary>
        internal static string CUSTOMER_NOT_FOUND {
            get {
                return ResourceManager.GetString("CUSTOMER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Adding Customer Details.
        /// </summary>
        internal static string ERROR_ADDING_CUSTOMER {
            get {
                return ResourceManager.GetString("ERROR_ADDING_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Generating OTP.
        /// </summary>
        internal static string ERROR_GENERATING_OTP {
            get {
                return ResourceManager.GetString("ERROR_GENERATING_OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging out.
        /// </summary>
        internal static string ERROR_LOGGING_OUT {
            get {
                return ResourceManager.GetString("ERROR_LOGGING_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating OrderStatus.
        /// </summary>
        internal static string ERROR_UPDATING_ORDER_STATUS {
            get {
                return ResourceManager.GetString("ERROR_UPDATING_ORDER_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating Vendor Base Rate.
        /// </summary>
        internal static string ERROR_UPDATING_VENDOR_BASE_RATE {
            get {
                return ResourceManager.GetString("ERROR_UPDATING_VENDOR_BASE_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating Vendor Services.
        /// </summary>
        internal static string ERROR_UPDATING_VENDOR_SERVICES {
            get {
                return ResourceManager.GetString("ERROR_UPDATING_VENDOR_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validating OTP.
        /// </summary>
        internal static string ERROR_VALIDATING_OTP {
            get {
                return ResourceManager.GetString("ERROR_VALIDATING_OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Authcode.
        /// </summary>
        internal static string INVALID_AUTHCODE {
            get {
                return ResourceManager.GetString("INVALID_AUTHCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Credentials.
        /// </summary>
        internal static string INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Details.
        /// </summary>
        internal static string INVALID_DETAILS {
            get {
                return ResourceManager.GetString("INVALID_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid old password.
        /// </summary>
        internal static string INVALID_OLD_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_OLD_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OTP.
        /// </summary>
        internal static string INVALID_OTP {
            get {
                return ResourceManager.GetString("INVALID_OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone Number Or OTP.
        /// </summary>
        internal static string INVALID_OTP_PHONENUMBER {
            get {
                return ResourceManager.GetString("INVALID_OTP_PHONENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token code.
        /// </summary>
        internal static string INVALID_TOKEN_CODE {
            get {
                return ResourceManager.GetString("INVALID_TOKEN_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login SuccessfulL.
        /// </summary>
        internal static string LOGIN_SUCCESSFULL {
            get {
                return ResourceManager.GetString("LOGIN_SUCCESSFULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Orders.
        /// </summary>
        internal static string NO_ORDERS {
            get {
                return ResourceManager.GetString("NO_ORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No orders for vendor.
        /// </summary>
        internal static string NO_ORDERS_FOR_VENDOR {
            get {
                return ResourceManager.GetString("NO_ORDERS_FOR_VENDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ratings for vendor.
        /// </summary>
        internal static string NO_RATINGS_FOR_VENDOR {
            get {
                return ResourceManager.GetString("NO_RATINGS_FOR_VENDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No services available.
        /// </summary>
        internal static string NO_SERVICES_AVAILABLE {
            get {
                return ResourceManager.GetString("NO_SERVICES_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sub services available.
        /// </summary>
        internal static string NO_SUB_SERVICES_AVAILABLE {
            get {
                return ResourceManager.GetString("NO_SUB_SERVICES_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors not found.
        /// </summary>
        internal static string NO_VENDORS {
            get {
                return ResourceManager.GetString("NO_VENDORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order not Confirmed.
        /// </summary>
        internal static string ORDER_NOT_CONFIRMED {
            get {
                return ResourceManager.GetString("ORDER_NOT_CONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order not found.
        /// </summary>
        internal static string ORDER_NOT_FOUND {
            get {
                return ResourceManager.GetString("ORDER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders not found.
        /// </summary>
        internal static string ORDERS_NOT_FOUND {
            get {
                return ResourceManager.GetString("ORDERS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete the selected service, as this service is in use..
        /// </summary>
        internal static string SERVICE_IN_USE {
            get {
                return ResourceManager.GetString("SERVICE_IN_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services not found.
        /// </summary>
        internal static string SERVICES_NOT_FOUND {
            get {
                return ResourceManager.GetString("SERVICES_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor not found.
        /// </summary>
        internal static string VENDOR_NOT_FOUND {
            get {
                return ResourceManager.GetString("VENDOR_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This vendor is already present in your favorite list..
        /// </summary>
        internal static string VENDOR_PRESENT_IN_FAVORITE_LIST {
            get {
                return ResourceManager.GetString("VENDOR_PRESENT_IN_FAVORITE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors are not found for the selected service.
        /// </summary>
        internal static string VENDORS_NOT_FOUND {
            get {
                return ResourceManager.GetString("VENDORS_NOT_FOUND", resourceCulture);
            }
        }
    }
}
