--------------------------------------------------------------------------------------------------------- 
--------------------------- All Copy Rights are reserved to Tasko.in-------------------------------------- 

---------------------------------------------------------------------------------------------------------- 
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CUSTOMER_PINCODE]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CUSTOMER_PINCODE](
	[Id] [binary](16) NOT NULL,
	[Pincode] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CustomerPincode] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500001')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500002')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500003')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500004')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500005')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500006')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500007')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500008')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500009')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500010')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500011')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500012')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500013')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500014')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500015')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500016')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500017')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500018')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500019')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500020')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500021')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500022')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500023')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500024')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500025')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500026')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500027')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500028')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500029')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500030')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500031')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500032')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500033')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500034')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500035')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500036')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500037')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500038')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500039')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500040')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500041')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500042')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500043')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500044')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500045')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500046')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500047')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500048')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500049')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500050')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500051')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500052')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500053')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500054')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500055')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500056')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500057')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500058')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500059')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500060')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500061')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500062')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500063')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500064')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500065')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500066')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500067')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500068')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500069')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500070')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500071')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500072')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500073')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500074')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500075')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500076')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500077')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500078')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500079')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500080')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500081')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500082')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500083')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500084')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500085')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500086')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500087')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500088')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500089')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500090')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500091')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500092')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500093')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500094')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500095')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500096')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500097')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500098')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500099')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500100')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '501510')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '502032')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500133')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '501401')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '502325')

END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[NEARBY_PINCODE]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[NEARBY_PINCODE](
	[PINCODE_ID] [binary](16) NOT NULL,
	[NEARBY_PINCODE_ID] [binary](16) NOT NULL,
	[DISTANCE] [varchar](50) NOT NULL,
 CONSTRAINT [PK_NEARBY_PINCODE] PRIMARY KEY CLUSTERED 
(
	[PINCODE_ID] ASC,
	[NEARBY_PINCODE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[NEARBY_PINCODE]  WITH CHECK ADD  CONSTRAINT [FK_NEARBY_PINCODE_CUSTOMER_PINCODE] FOREIGN KEY([PINCODE_ID])
REFERENCES [dbo].[CUSTOMER_PINCODE] ([Id])

ALTER TABLE [dbo].[NEARBY_PINCODE] CHECK CONSTRAINT [FK_NEARBY_PINCODE_CUSTOMER_PINCODE]

ALTER TABLE [dbo].[NEARBY_PINCODE]  WITH CHECK ADD  CONSTRAINT [FK_NEARBY_PINCODE_CUSTOMER_PINCODE1] FOREIGN KEY([NEARBY_PINCODE_ID])
REFERENCES [dbo].[CUSTOMER_PINCODE] ([Id])

ALTER TABLE [dbo].[NEARBY_PINCODE] CHECK CONSTRAINT [FK_NEARBY_PINCODE_CUSTOMER_PINCODE1]

ALTER TABLE [dbo].[NEARBY_PINCODE]  WITH CHECK ADD  CONSTRAINT [FK_NEARBY_PINCODE_NEARBY_PINCODE] FOREIGN KEY([PINCODE_ID], [NEARBY_PINCODE_ID])
REFERENCES [dbo].[NEARBY_PINCODE] ([PINCODE_ID], [NEARBY_PINCODE_ID])

ALTER TABLE [dbo].[NEARBY_PINCODE] CHECK CONSTRAINT [FK_NEARBY_PINCODE_NEARBY_PINCODE]

END

GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[usp_GetOfflineServiceVendors]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[usp_GetOfflineServiceVendors] AS' 
END
GO

ALTER PROCEDURE [dbo].[usp_GetOfflineServiceVendors]
(
  @pServiceId binary(16),
  @pCustomerId binary(16),
  @pPinCode varchar(10)
)

AS
BEGIN

SET NOCOUNT ON;

    DECLARE @pincodeId binary(16)
    SELECT @pincodeId = ID FROM CUSTOMER_PINCODE WHERE Pincode =@pPinCode
	IF LEN(@pincodeId) >0
	  BEGIN
		SELECT SVC.SERVICE_ID ,SVC.NAME AS SERVICE_NAME, V.VENDOR_ID, V.NAME AS VENDOR_NAME,VENDOR_SERVICE_ID, V.BASE_RATE, CV.FAVORITE_ID, A.LATITIUDE AS LATITIUDE, A.LONGITUDE AS LONGITUDE,
		A.pincode,
		(SELECT COUNT(*) FROM VENDOR_RATING VR WHERE VR.VENDOR_ID = V.VENDOR_ID)AS TOTAL_REVIEWS, dbo.[GetVendorTotalRating](V.VENDOR_ID) AS OVERALL_RATINGS,V.FACEBOOK_URL,V.PHOTO	
		FROM [dbo].[SERVICES] SVC
		INNER JOIN [dbo].[VENDOR_SERVICES] VS ON VS.SERVICE_ID = SVC.SERVICE_ID
		INNER JOIN [dbo].[VENDOR] V ON V.VENDOR_ID = VS.VENDOR_ID
		INNER JOIN [ADDRESS] A ON V.ADDRESS_ID = A.ADDRESS_ID
		LEFT OUTER JOIN [dbo].[CUSTOMER_FAVORITE_VENDOR] CV ON CV.CUSTOMER_ID = @pCustomerId AND CV.VENDOR_ID = V.VENDOR_ID
		WHERE SVC.SERVICE_ID = @pServiceId AND VS.IS_VENDOR_SERVICE_ACTIVE = 1 AND 
		A.PINCODE IN(SELECT PINCODE FROM CUSTOMER_PINCODE 
		WHERE ID IN(SELECT NEARBY_PINCODE_ID FROM NEARBY_PINCODE WHERE PINCODE_ID = @pincodeId)) 

		UNION ALL
		SELECT SVC.SERVICE_ID ,SVC.NAME AS SERVICE_NAME, V.VENDOR_ID, V.NAME AS VENDOR_NAME,VENDOR_SERVICE_ID, V.BASE_RATE, CV.FAVORITE_ID, A.LATITIUDE AS LATITIUDE, A.LONGITUDE AS LONGITUDE,
		A.pincode,
		(SELECT COUNT(*) FROM VENDOR_RATING VR WHERE VR.VENDOR_ID = V.VENDOR_ID)AS TOTAL_REVIEWS, dbo.[GetVendorTotalRating](V.VENDOR_ID) AS OVERALL_RATINGS,V.FACEBOOK_URL,V.PHOTO	
		FROM [dbo].[SERVICES] SVC
		INNER JOIN [dbo].[VENDOR_SERVICES] VS ON VS.SERVICE_ID = SVC.SERVICE_ID
		INNER JOIN [dbo].[VENDOR] V ON V.VENDOR_ID = VS.VENDOR_ID
		INNER JOIN [ADDRESS] A ON V.ADDRESS_ID = A.ADDRESS_ID
		LEFT OUTER JOIN [dbo].[CUSTOMER_FAVORITE_VENDOR] CV ON CV.CUSTOMER_ID = @pCustomerId AND CV.VENDOR_ID = V.VENDOR_ID
		WHERE SVC.SERVICE_ID = @pServiceId AND VS.IS_VENDOR_SERVICE_ACTIVE = 1 AND 
		A.PINCODE = @pPinCode order by a.pincode
	  END
END

GO

--500001
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500001'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'), '1.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500001'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'), '2.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500001'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'), '3.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500001'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500054'), '3.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500001'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500028'), '3.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500001'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500002'), '4.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500001'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500044'), '4.7')
--500002
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500002'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500082'), '5.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500002'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500059'), '4.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500002'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500036'), '2.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500002'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500001'), '4.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500002'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500064'), '3.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500002'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'), '2.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500002'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'), '5.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500002'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500023'), '1.5')
--500003
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'), '3.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500016'), '3.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'), '3.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500015'), '2.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500011'), '5.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500025'), '3.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500026'), '1.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500009'), '3.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'), '3.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500048'), '2.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500061'), '2.4')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500017'), '3.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500007'), '5.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'), '5.8')
--500004
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500082'), '3.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'), '2.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500016'), '5.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500073'), '4.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500054'), '2.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500045'), '6.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'), '5.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500018'), '5.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500001'), '5.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'), '6.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'), '2.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'), '5.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500028'), '4.1')
--500005
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500005'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500035'), '2.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500005'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500010'), '4.4')
--500006
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500006'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500028'), '4.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500006'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500008'), '6.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500006'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'), '3.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500006'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500001'), '3.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500006'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'), '1.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500006'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500036'), '4.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500006'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500002'), '2.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500006'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500065'), '5.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500006'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500023'), '4.4')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500006'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500064'), '3.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500006'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500053'), '4.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500006'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'), '4.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500006'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500048'), '5.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500006'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'), '4.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500006'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500034'), '5.7')
--500007
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500007'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500076'), '1.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500007'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500007'), '3.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500007'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500061'), '4.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500007'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500047'), '5.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500007'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500017'), '3.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500007'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500025'), '3.4')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500007'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500044'), '4.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500007'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500013'), '5.4')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500007'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500039'), '5.6')
--500008
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500008'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500028'), '6.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500008'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500048'), '4.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500008'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500089'), '5.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500008'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500096'), '5.3')
--500009
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500009'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500010'), '1.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500009'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500011'), '3.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500009'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500015'), '3.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500009'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500048'), '5.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500009'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'), '4.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500009'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500037'), '6.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500009'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500016'), '4.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500009'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500026'), '3.2')
--500010
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500010'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'), '4.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500010'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='502325'), '5.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500010'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='501401'), '3.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500010'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500055'), '4.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500010'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500087'), '6.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500010'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500094'), '6.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500010'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500015'), '4.5')
--500011
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500011'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500015'), '1.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500011'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500037'), '5.4')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500011'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'), '5.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500011'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500026'), '4.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500011'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500009'), '3.7')
--500012
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500055'), '4.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500001'), '2.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'), '4.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'), '5.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500028'), '6.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'), '5.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500044'), '5.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'), '1.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500095'), '3.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500006'), '2.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500036'), '3.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'), '4.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500023'), '3.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500002'), '2.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500065'), '4.4')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'), '3.8')
--500013
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500013'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500002'), '3.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500013'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500060'), '4.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500013'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500007'), '3.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500013'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500044'), '3.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500013'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'), '3.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500013'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500061'), '5.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500013'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500036'), '4.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500013'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500059'), '4.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500013'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'), '5.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500013'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'), '5.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500013'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500001'), '3.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500013'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500048'), '4.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500013'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'), '4.3')
--500014
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500014'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='501401'), '5.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500014'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500010'), '4.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500014'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500055'), '5.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500014'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500054'), '6.3')
--500015
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500015'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500010'), '4.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500015'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'), '5.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500015'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500094'), '5.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500015'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500087'), '5.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500015'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500056'), '5.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500015'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500026'), '5.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500015'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500011'), '4.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500015'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500009'), '3.9')
--500016
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500016'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500056'), '3.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500016'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'), '2.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500016'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500016'), '3.4')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500016'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500038'), '4.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500016'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500009'), '5.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500016'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500015'), '6.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500016'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500026'), '5.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500016'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500048'), '5.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500016'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'), '5.4')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500016'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500082'), '5.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500016'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500037'), '4.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500016'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500018'), '3.2')
--500017
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500017'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500038'), '4.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500017'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'), '4.4')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500017'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500026'), '2.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500017'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500047'), '5.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500017'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500007'), '5.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500017'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500076'), '4.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500017'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'), '4.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500017'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500025'), '5.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500017'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500061'), '5.0')
--500018
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500018'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500071'), '3.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500018'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500016'), '3.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500018'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500038'), '2.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500018'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500037'), '4.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500018'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500081'), '5.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500018'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500082'), '5.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500018'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500045'), '3.5')
--500019
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500019'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500045'), '2.4')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500019'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500049'), '6.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500019'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500050'), '1.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500019'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='502032'), '1.9')
--500020
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500050'), '5.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500025'), '5.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'), '3.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500048'), '3.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500061'), '4.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500044'), '3.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500013'), '4.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'), '2.4')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'), '1.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500007'), '5.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'), '5.4')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'), '4.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500001'), '2.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'), '5.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500082'), '5.3')
--500022
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500022'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'), '2.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500022'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500044'), '5.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500022'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'), '5.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500022'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'), '4.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500022'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500048'), '4.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500022'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500016'), '5.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500022'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500018'), '6.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500022'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500082'), '3.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500022'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'), '2.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500022'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500034'), '4.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500022'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500028'), '5.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500022'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500001'), '4.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500022'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'), '5.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500022'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'), '5.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500022'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500095'), '3.7')
--500023
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500023'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'), '2.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500023'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500002'), '1.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500023'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500065'), '2.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500023'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500059'), '1.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500023'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500078'), '3.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500023'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500053'), '5.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500023'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500079'), '5.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500023'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500036'), '5.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500023'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'), '2.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500023'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'), '3.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500023'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500001'), '4.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500023'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500006'), '4.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500023'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'), '5.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500023'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500023'), '1.0')
--500024
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500002'), '2.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500023'), '2.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500064'), '5.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500065'), '4.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500001'), '3.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500036'), '1.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500059'), '2.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500079'), '4.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500060'), '4.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500008'), '3.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500044'), '4.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'), '3.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'), '4.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'), '5.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500006'), '4.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500013'), '3.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500095'), '3.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500035'), '3.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500061'), '1.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'), '3.6')
--500025
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500025'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'), '3.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500025'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500048'), '3.4')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500025'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500017'), '3.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500025'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500026'), '4.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500025'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500007'), '5.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500025'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500044'), '3.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500025'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'), '5.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500025'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'), '2.4')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500025'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'), '3.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500025'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500061'), '1.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500025'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500076'), '4.8')
--500026
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500026'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500016'), '5.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500026'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500009'), '3.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500026'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'), '1.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500026'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500015'), '3.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500026'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500011'), '5.4')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500026'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500017'), '3.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500026'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500061'), '2.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500026'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500007'), '5.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500026'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'), '5.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500026'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500025'), '3.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500026'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500048'), '3.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500026'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500044'), '2.0')
--500027
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500013'), '3.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500044'), '2.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500001'), '1.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'), '1.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'), '4.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'), '3.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500095'), '2.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500023'), '5.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500002'), '4.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'), '3.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500061'), '4.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'), '4.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500025'), '5.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'), '4.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500048'), '1.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500028'), '3.4')
--500028
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500028'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'), '2.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500028'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500008'), '5.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500028'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500034'), '3.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500028'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500082'), '4.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500028'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'), '4.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500028'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500001'), '3.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500028'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'), '5.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500028'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500006'), '5.2')
--500029
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'), '4.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500001'), '1.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500028'), '5.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500082'), '5.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500044'), '3.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500020'), '1.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500013'), '5.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500003'), '3.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500048'), '4.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500016'), '5.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500027'), '2.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500012'), '4.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500036'), '4.4')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500029'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500024'), '4.8')
--500030
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500030'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500086'), '3.2')
--500031
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500031'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500008'), '6.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500031'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500081'), '6.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500031'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500089'), '4.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500031'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500048'), '4.4')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500031'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500075'), '4.2')
--500032
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500032'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500008'), '3.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500032'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500084'), '5.4')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500032'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500081'), '4.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500032'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500033'), '5.0')
--500033
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500033'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500045'), '3.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500033'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500073'), '4.4')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500033'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500018'), '5.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500033'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500008'), '5.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500033'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500081'), '4.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500033'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500096'), '2.7')
--500034
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500034'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500004'), '4.2')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500034'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500082'), '2.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500034'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500008'), '2.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500034'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500073'), '4.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500034'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500048'), '4.7')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500034'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500016'), '5.6')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500034'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500018'), '5.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500034'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500045'), '5.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500034'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500028'), '5.0')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500034'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500096'), '5.4')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500034'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500001'), '5.6')
--500072
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500072'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500049'), '2.5')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500072'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500037'), '3.1')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500072'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500018'), '5.5')
--500049
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500049'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500050'), '3.9')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500049'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500032'), '2.8')
--500081
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500081'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500018'), '3.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500081'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500032'), '4.8')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500081'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500072'), '5.3')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500081'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500084'), '3.4')
INSERT INTO NEARBY_PINCODE VALUES ((SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500081'),(SELECT Id FROM CUSTOMER_PINCODE WHERE Pincode ='500033'), '4.0')

IF NOT EXISTS (SELECT * FROM [dbo].[DB_VERSION] WHERE [VERSION] = '3.0.0.0')
BEGIN
     INSERT INTO [dbo].[DB_VERSION] values('3.0.0.0', Getdate())
END
GO