--------------------------------------------------------------------------------------------------------- 
--------------------------- All Copy Rights are reserved to Tasko.in-------------------------------------- 

---------------------------------------------------------------------------------------------------------- 
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CUSTOMER_PINCODE]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CUSTOMER_PINCODE](
	[Id] [binary](16) NOT NULL,
	[Pincode] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CustomerPincode] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500001')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500002')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500003')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500004')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500005')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500006')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500007')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500008')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500009')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500010')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500011')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500012')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500013')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500014')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500015')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500016')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500017')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500018')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500019')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500020')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500021')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500022')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500023')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500024')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500025')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500026')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500027')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500028')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500029')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500030')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500031')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500032')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500033')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500034')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500035')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500036')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500037')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500038')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500039')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500040')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500041')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500042')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500043')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500044')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500045')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500046')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500047')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500048')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500049')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500050')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500051')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500052')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500053')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500054')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500055')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500056')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500057')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500058')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500059')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500060')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500061')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500062')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500063')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500064')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500065')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500066')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500067')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500068')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500069')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500070')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500071')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500072')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500073')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500074')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500075')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500076')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500077')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500078')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500079')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500080')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500081')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500082')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500083')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500084')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500085')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500086')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500087')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500088')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500089')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500090')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500091')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500092')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500093')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500094')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500095')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500096')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500097')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500098')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500099')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500100')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '501510')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '502032')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '500133')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '501401')
INSERT INTO CUSTOMER_PINCODE VALUES  (newid(), '502325')

END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[NEARBY_PINCODE]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[NEARBY_PINCODE](
	[PINCODE_ID] [binary](16) NOT NULL,
	[NEARBY_PINCODE_ID] [binary](16) NOT NULL,
	[DISTANCE] [varchar](50) NOT NULL,
 CONSTRAINT [PK_NEARBY_PINCODE] PRIMARY KEY CLUSTERED 
(
	[PINCODE_ID] ASC,
	[NEARBY_PINCODE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[NEARBY_PINCODE]  WITH CHECK ADD  CONSTRAINT [FK_NEARBY_PINCODE_CUSTOMER_PINCODE] FOREIGN KEY([PINCODE_ID])
REFERENCES [dbo].[CUSTOMER_PINCODE] ([Id])

ALTER TABLE [dbo].[NEARBY_PINCODE] CHECK CONSTRAINT [FK_NEARBY_PINCODE_CUSTOMER_PINCODE]

ALTER TABLE [dbo].[NEARBY_PINCODE]  WITH CHECK ADD  CONSTRAINT [FK_NEARBY_PINCODE_CUSTOMER_PINCODE1] FOREIGN KEY([NEARBY_PINCODE_ID])
REFERENCES [dbo].[CUSTOMER_PINCODE] ([Id])

ALTER TABLE [dbo].[NEARBY_PINCODE] CHECK CONSTRAINT [FK_NEARBY_PINCODE_CUSTOMER_PINCODE1]

ALTER TABLE [dbo].[NEARBY_PINCODE]  WITH CHECK ADD  CONSTRAINT [FK_NEARBY_PINCODE_NEARBY_PINCODE] FOREIGN KEY([PINCODE_ID], [NEARBY_PINCODE_ID])
REFERENCES [dbo].[NEARBY_PINCODE] ([PINCODE_ID], [NEARBY_PINCODE_ID])

ALTER TABLE [dbo].[NEARBY_PINCODE] CHECK CONSTRAINT [FK_NEARBY_PINCODE_NEARBY_PINCODE]

END

GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[usp_GetOfflineServiceVendors]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[usp_GetOfflineServiceVendors] AS' 
END
GO

ALTER PROCEDURE [dbo].[usp_GetOfflineServiceVendors]
(
  @pServiceId binary(16),
  @pCustomerId binary(16),
  @pPinCode varchar(10)
)

AS
BEGIN

SET NOCOUNT ON;

    DECLARE @pincodeId binary(16)
    SELECT @pincodeId = ID FROM CUSTOMER_PINCODE WHERE Pincode =@pPinCode

    SELECT SVC.SERVICE_ID ,SVC.NAME AS SERVICE_NAME, V.VENDOR_ID, V.NAME AS VENDOR_NAME,VENDOR_SERVICE_ID, V.BASE_RATE, CV.FAVORITE_ID, A.LATITIUDE AS LATITIUDE, A.LONGITUDE AS LONGITUDE,
	(SELECT COUNT(*) FROM VENDOR_RATING VR WHERE VR.VENDOR_ID = V.VENDOR_ID)AS TOTAL_REVIEWS, dbo.[GetVendorTotalRating](V.VENDOR_ID) AS OVERALL_RATINGS,V.FACEBOOK_URL,V.PHOTO	
	FROM [dbo].[SERVICES] SVC
	INNER JOIN [dbo].[VENDOR_SERVICES] VS ON VS.SERVICE_ID = SVC.SERVICE_ID
	INNER JOIN [dbo].[VENDOR] V ON V.VENDOR_ID = VS.VENDOR_ID
	INNER JOIN [ADDRESS] A ON V.ADDRESS_ID = A.ADDRESS_ID
	LEFT OUTER JOIN [dbo].[CUSTOMER_FAVORITE_VENDOR] CV ON CV.CUSTOMER_ID = @pCustomerId AND CV.VENDOR_ID = V.VENDOR_ID
	WHERE SVC.SERVICE_ID = @pServiceId AND VS.IS_VENDOR_SERVICE_ACTIVE = 1 AND 
	A.PINCODE IN((SELECT PINCODE FROM CUSTOMER_PINCODE 
	WHERE ID IN(SELECT NEARBY_PINCODE_ID FROM NEARBY_PINCODE WHERE PINCODE_ID = @pincodeId)), @pPinCode)
	
END

GO


IF NOT EXISTS (SELECT * FROM [dbo].[DB_VERSION] WHERE [VERSION] = '3.0.0.0')
BEGIN
     INSERT INTO [dbo].[DB_VERSION] values('3.0.0.0', Getdate())
END
GO
